library(quantmod)
library(xts)
library(zoo)
library(TTR)
setSymbolLookup(WK=list(name='300015.sz',src='yahoo'))
getSymbols("WK",from="2018-05-21",to="2018-06-22")
dim(WK)
head(WK)
chartSeries(WK,up.col='red', dn.col='green', TA=c(#addMACD(),
                                                  addSMA(n=5,col="white"),addSMA(n=10,col="yellow")))
